### ISSUE TITLE
defining the path to various programs

### ISSUE THREAD

**Issue by jenncoughlan** [johanzi/gwas_gemma#1]
Hello!
I'm currently using GEMMA for the first time and your pipeline looks like it'll be really useful. However, I'm having a mild issue trying to find where I can define the paths to PLINK and GEMMA in "run_gwas_gemma.sh" . So far, I've tried simply placing the script in the same directory as GEMMA, but that didn't seem to solve the issue and a "gemma required  but it's not installed. Aborting" error was given. 

Any help would be wonderful!
Thanks so much,
Jenn

**Comment by johanzi** [comment]
Hi Jenn,
Sorry for the very late answer. Did you solve your problem?
It is not a good practice to put software binaries where you run your analysis. You usually put them somewhere like "/users/jenn/bin/" and then add the location of the binary for each software to your variable $PATH. Then you should be able to call them by typing "gemma" or "plink". That is rather basic Linux knowledge so maybe you should read a bit more about that before trying to run bash scripts.
Good luck!
Best
Johan
