### ISSUE TITLE
would GEMMA be appropriate for RIL?

### ISSUE THREAD

**Issue by adriludwig** [johanzi/gwas_gemma#2]
Hi! We've done bulk segregation experiments (RIL) but we end up sequencing individuals from the two extreme groups instead of sequencing pools. I'm wondering if I could use GEMMA for a GWAS analysis since it could correct for relatedness (considering I have an interbred population). Would GEMMA be appropriate? Thanks very much

**Comment by johanzi** [comment]
Hi, sorry for the late reply. For a BSA, I would recommend the pipeline of my colleague Emmanuel Tergemina, he used it in this paper https://www.science.org/doi/10.1126/sciadv.abm9385 and you can find the script there https://github.com/HancockLab/Fogo-Edaphic/tree/main/Main/Figure2/Fig2C
